### ISSUE TITLE
Improve error handling in gdown

### ISSUE THREAD

**Issue by philtgun** [MTG/mtg-jamendo-dataset#17]
Properly handle disconnections when downloading from gdrive. If possible - resume download.

```
Downloading...
From: https://drive.google.com/uc?id=1tRY9wO_RYA_1JIPvNkuib7v7G1kGf7gQ
To: ..../jamendo-dataset/raw_30s_audio-06.tar
1.59GB [00:49, 37.8MB/s]('Connection broken: IncompleteRead(467461 bytes read, 56827 more expected)', IncompleteRead(467461 bytes read, 56827 more expected))
Traceback (most recent call last):
  File "scripts/download/download_gdrive.py", line 121, in <module>
    download(args.dataset, args.type, args.outputdir, args.unpack, args.remove)
  File "scripts/download/download_gdrive.py", line 61, in download
    if compute_sha256(output) != sha256_tars[filename]:
  File "scripts/download/download_gdrive.py", line 16, in compute_sha256
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '..../jamendo-dataset/raw_30s_audio-06.tar'
1.59GB [00:54, 29.4MB/s]
```

**Comment by AmitSharma1127** [comment]
This issue still persists. Is someone working on this?

**Comment by dbogdanov** [comment]
Disabled Google Drive downloads in 5e80e0c0009decd279dd7cf67d1d2711a69c0c74. Use `mtg` or `mtg-fast` mirrors for downloads.
